#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { CharacterCatalog } = require('../catalog/character_catalog');

function buildCharacterCatalog(baseDir = path.join(__dirname, '..')) {
  const root = path.resolve(baseDir);
  const catalog = CharacterCatalog.load(root, { validateAssets: true });
  const snapshot = catalog.toSnapshot();
  const outputDir = path.join(root, 'catalog', 'generated');
  const jsonPath = path.join(outputDir, 'character_catalog.json');
  const browserPath = path.join(outputDir, 'character_catalog.browser.js');
  const serialized = `${JSON.stringify(snapshot, null, 2)}\n`;

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(jsonPath, serialized, 'utf8');
  fs.writeFileSync(
    browserPath,
    `/* Generated by scripts/build_character_catalog.js — do not edit. */\nwindow.WWL_CHARACTER_CATALOG = ${serialized.trim()};\n`,
    'utf8',
  );

  return {
    character_count: snapshot.characters.length,
    json_path: jsonPath,
    browser_path: browserPath,
  };
}

if (require.main === module) {
  try {
    const result = buildCharacterCatalog();
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    if (Array.isArray(error.issues)) {
      process.stderr.write(`${JSON.stringify(error.issues, null, 2)}\n`);
    }
    process.exitCode = 1;
  }
}

module.exports = { buildCharacterCatalog };
