#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { VisualCatalog } = require('./visual_catalog');

function buildVisualCatalog(baseDir = path.join(__dirname, '..'), { write = true } = {}) {
  const root = path.resolve(baseDir);
  const catalog = VisualCatalog.load(root, { validateAssets: true });
  const snapshot = catalog.toSnapshot();
  const outputDir = path.join(root, 'generated');
  const browserPath = path.join(outputDir, 'visual_catalog.browser.js');
  const serialized = `${JSON.stringify(snapshot, null, 2)}\n`;
  const browserCode = `/* Generated by tools/build.js — do not edit. */\nwindow.WWL_VISUAL_CATALOG = ${serialized.trim()};\n`;

  if (write) {
    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(browserPath, browserCode, 'utf8');
  }

  return {
    character_count: snapshot.characters.length,
    browser_path: browserPath,
    snapshot,
    browser_code: browserCode,
  };
}

if (require.main === module) {
  try {
    const write = !process.argv.includes('--check');
    const result = buildVisualCatalog(undefined, { write });
    process.stdout.write(`${JSON.stringify({
      character_count: result.character_count,
      browser_path: result.browser_path,
      mode: write ? 'built' : 'checked',
    }, null, 2)}\n`);
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    if (Array.isArray(error.issues)) {
      process.stderr.write(`${JSON.stringify(error.issues, null, 2)}\n`);
    }
    process.exitCode = 1;
  }
}

module.exports = { buildVisualCatalog };
